### ISSUE TITLE
Logo licenses

### ISSUE THREAD

**Issue by kimimaru4000** [MonoGame/MonoGame.Logo#5]
I noticed that licenses are missing for the logos, but I don't want to assume that they're under the same license as the MonoGame framework itself. Is it possible to clarify which license the logos are under?

**Comment by tomspilman** [comment]
This is a good point @kimimaru4000 .

It was suggested for us to look at the [Blender logo usage](https://www.blender.org/about/logo/) page.

If we added a section to the readme.md that has some similar notations and limitations that would work.

- The MonoGame logo is a brand for official MonoGame projects and content.
- The MonoGame logo is a [registered trademark](https://trademarks.justia.com/864/56/monogame-86456908.html).
- The MonoGame logo and brand is not open source.
- The logo can be used to link to the MonoGame project.
- The logo can be used to credit MonoGame in your own works.
- 
Or something like that.

**Comment by kimimaru4000** [comment]
I'm not a lawyer, but to me the Blender logo usage guidelines sound similar to the [Attribution-NonCommercial-NoDerivs
(CC BY-NC-ND)](https://creativecommons.org/licenses/by-nc-nd/4.0/) license.

In short, this allows others to share the logos as long as they provide attribution, and it does not allow altering the logos or using them commercially.

However, I'm unsure exactly how this license covers trademarks, if it even does. Thoughts?

**Comment by mrhelmut** [comment]
CC BY might allow usages beyond giving credits (e.g. using the logo for the fists of a playable character in a free game).

I believe that the Blender license is the closest to what using a logo may be.

In a similar way, there's the [FMOD attribution](https://www.fmod.com/attribution), though it might be too restrictive in our situation because it forces to have the logo displayed (which we might want to have as an option in our case?).
I believe that we shouldn't have a logo license that is more restrictive in terms of crediting than the MS-PL. So yeah, Blender.
